[phases.setup]
nixPkgs = [
  # Core image libraries with development headers
  "zlib.dev",
  "libjpeg.dev",
  "libpng.dev",
  "libtiff.dev",
  "freetype.dev",
  "lcms2.dev",
  "openjpeg.dev",
  
  # Build tools
  "pkg-config",
  "gcc",
  "make",
  
  # Python and database
  "python312Full",
  "postgresql",
  
  # Other dependencies
  "libffi",
  "openssl",
  
  # OCR
  "tesseract-ocr"
]

[phases.build]
cmds = [
  # Set environment variables to help find libraries
  "export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${LIBRARY_PATH}/pkgconfig",
  
  # Install Pillow first with explicit build requirements
  "CFLAGS=\"-I${LIBRARY_PATH}/include\" pip install --no-cache-dir --force-reinstall --no-binary :all: pillow==9.5.0",
  
  # Then install the rest
  "pip install --no-cache-dir -r requirements.txt"
]

[build]
packages = ["tesseract-ocr"]