[phases.setup]
nixPkgs = ["zlib", "libjpeg", "pkg-config", "gcc", "python312Full"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "./.railway/entrypoint.sh"
