[phases.setup]
nixPkgs = [
  "zlib",
  "libjpeg",
  "pkg-config",
  "gcc",
  "python312Full",
  "libpq",       # For PostgreSQL support
  "postgresql",  # For pg_config
  "libffi",      # For cffi
  "openssl",     # For SSL support
  "libpng",      # For Pillow PNG support
  "tesseract-ocr" # Already in your build packages
]

[phases.build]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "./.railway/entrypoint.sh"

[build]
packages = ["tesseract-ocr"]