# Generated by Django 4.2.1 on 2025-07-15 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_payment_options_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='user',
            field=models.OneToOneField(default='2024-01-01 00:00:00', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='activated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
