# Generated by Django 4.2.1 on 2025-07-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_premiumuser_user_alter_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='activated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
